name: CI/CD

on:
  push:
    branches:
      - feature/setup-application

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Set the Python version

    - name: Install dependencies including pytest
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run unit tests
      run: pytest

  merge-to-main:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/feature/setup-application' && github.event_name == 'push' && github.event_name != 'pull_request'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Merge to main
      if: success()
      run: |
        git fetch origin main:main
        git checkout main
        git merge --no-ff origin/main
        git push origin main
      env:
        PAT: ${{ secrets.PAT }}

  manager-approval:
    runs-on: ubuntu-latest
    needs: merge-to-main
    if: github.ref == 'refs/heads/main' && github.event_name == 'push' && github.event_name != 'pull_request'

    steps:
    - name: Request manager approval
      uses: "marvinpinto/action-automatic-rebase@v2"
      with:
        comment: "This pull request is awaiting manager approval for merge."
